version: 0.2

env:
  variables:
    AWS_REGION: us-east-2
    ECR_REPOSITORY_NAME: crm-api-repo

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Instalando dependências..."

  pre_build:
    commands:
      - echo "Restaurando dependências..."
      - dotnet restore src/CRM-API.sln

  build:
    commands:
      - echo "Build do projeto"
      - dotnet build src/CRM-API.sln --configuration Release
      - dotnet publish src/CRM-API/CRM-API.csproj -c Release -o ./app

  post_build:
    commands:
      - echo "Build concluído."

artifacts:
  files:
    - app/**/*

