    # ... (código anterior do buildspec.yml) ...

    post_build:
      commands:
        - echo "Pós-build: Gerando pacote de deploy (deploy.zip)..."
        # Cria o Dockerrun.aws.json com a imagem ECR atualizada
        - |
          cat > Dockerrun.aws.json <<EOF
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": 80
              }
            ],
            "Logging": "/var/log/nginx"
          }
          EOF
        - echo "Dockerrun.aws.json criado com sucesso."
        # Zip o Dockerrun.aws.json e o diretório .ebextensions
        - zip -r deploy.zip Dockerrun.aws.json .ebextensions/
        - echo "Pacote de deploy (deploy.zip) criado."
        - echo "Verificando conteúdo do deploy.zip:" # <-- NOVO
        - ls -l deploy.zip # <-- NOVO
        - unzip -l deploy.zip # <-- NOVO

    artifacts:
      files:
        - deploy.zip
      discard-paths: yes
    