version: 0.2

env:
  variables:
    AWS_REGION: us-east-2
    AWS_ACCOUNT_ID: 679625722040
    ECR_REPOSITORY_NAME: crm-api-repo

phases:
  install:
    commands:
      - echo "Instalando .NET SDK..."
      - apt-get update -y
      - apt-get install -y dotnet-sdk-8.0

      - echo "Instalando utilitário zip..."
      - apt-get install -y zip

  pre_build:
    commands:
      - echo "Fazendo login no Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Restaurando dependências .NET..."
      - dotnet restore CRM-API.sln

      - echo "Construindo a API .NET..."
      - dotnet build CRM-API.sln --no-restore --configuration Release

      - echo "Executando testes unitários..."
      - dotnet test src/CRM.Tests/CRM.Tests.csproj --no-build --verbosity normal --configuration Release

      - echo "Construindo e empurrando a imagem Docker para o ECR..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG -f Dockerfile .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG

      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest

      - echo "Criando Dockerrun.aws.json..."
      - |
        cat > Dockerrun.aws.json <<EOF
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": 80
            }
          ],
          "Logging": "/var/log/nginx"
        }
        EOF
      - echo "Dockerrun.aws.json criado com sucesso."

      - echo "Gerando pacote de deploy (deploy.zip)..."
      - zip -r deploy.zip Dockerrun.aws.json

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
