version: 0.2

env:
  variables:
    AWS_REGION: us-east-2
    ECR_REPOSITORY_NAME: crm-api-repo

phases:
  install:
    commands:
      - echo "Instalando .NET SDK..."
      - apt-get update -y
      - apt-get install -y dotnet-sdk-8.0

      - echo "Instalando utilitário zip..."
      - apt-get install -y zip

      # Comandos de depuração (opcional, pode remover na versão final)
      - echo "Listando conteúdo da raiz do diretório de trabalho do CodeBuild:"
      - ls -F .
      - echo "Listando conteúdo de src/ (se existir):"
      - ls -F src/ || true

  pre_build:
    commands:
      - echo "Recuperando AWS_ACCOUNT_ID..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - echo "Fazendo login no Amazon ECR..."
      # CORRIGIDO: Usando 'bash -c' para envolver o comando de login no ECR
      - bash -c "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

  build:
    commands:
      # Copia todo o conteúdo da raiz do repositório para um diretório temporário
      # e muda para ele. Isso garante que o contexto de build seja consistente.
      - cp -R . /tmp/build_src/
      - cd /tmp/build_src/

      - echo "Restaurando dependências .NET..."
      - dotnet restore src/CRM-API.sln

      - echo "Construindo a API .NET..."
      - dotnet build src/CRM-API.sln --no-restore --configuration Release

      - echo "Executando testes unitários..."
      - dotnet test src/CRM.Tests/CRM.Tests.csproj --no-build --verbosity normal --configuration Release

      - echo "Construindo e empurrando a imagem Docker para o ECR..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG -f Dockerfile .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG

      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest

      - echo "Criando Dockerrun.aws.json..."
      - echo '{"AWSEBDockerrunVersion":"1","Image":{"Name":"'$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/'$ECR_REPOSITORY_NAME':latest","Update":"true"},"Ports":[{"ContainerPort":80}],"Logging":"/var/log/nginx"}' > Dockerrun.aws.json
      - echo "Dockerrun.aws.json criado com sucesso."

      - echo "Gerando pacote de deploy (deploy.zip)..."
      - zip -r deploy.zip Dockerrun.aws.json
      # NOVO: Copia o deploy.zip para o diretório raiz do CodeBuild
      - mv deploy.zip /codebuild/output/src110233707/src/deploy.zip # Ajuste o caminho de destino para o CODEBUILD_SRC_DIR

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
