version: 0.2

env:
  variables:
    AWS_REGION: us-east-2
    ECR_REPOSITORY_NAME: crm-api-repo

phases:
  install:
    commands:
      - echo "Instalando .NET SDK..."
      - apt-get update -y
      - apt-get install -y dotnet-sdk-8.0

      - echo "Instalando utilitário zip..."
      - apt-get install -y zip

  pre_build:
    commands:
      - echo "Recuperando AWS_ACCOUNT_ID..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"

  build:
    commands:
      - echo "Restaurando dependências .NET..."
      - dotnet restore src/CRM-API.sln

      - echo "Construindo a API .NET..."
      - dotnet build src/CRM-API.sln --no-restore --configuration Release

      - echo "Executando testes unitários..."
      - dotnet test src/CRM.Tests/CRM.Tests.csproj --no-build --verbosity normal --configuration Release

      - echo "Construindo e empurrando a imagem Docker para o ECR..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG -f Dockerfile .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG

      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
            - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - echo "Construindo e empurrando a imagem Docker para o ECR..."
            - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG -f Dockerfile .
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG
      - echo "Criando Dockerrun.aws.json..."
      - echo '{"AWSEBDockerrunVersion":"1","Image":{"Name":"'$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/'$ECR_REPOSITORY_NAME':latest","Update":"true"},"Ports":[{"ContainerPort":80}],"Logging":"/var/log/nginx"}' > Dockerrun.aws.json
      - echo "Dockerrun.aws.json criado com sucesso."

      - echo "Gerando pacote de deploy (deploy.zip)..."
      - zip -r deploy.zip Dockerrun.aws.json

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
